name: spimaging-runtime-cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip=25.1
  - numpy=1.26.4
  - h5py=3.16.0
  - imageio=2.37.0
  - scikit-image=0.25.2
  - matplotlib=3.10.9
  - tqdm=4.69.0
  - opencv=4.11
  - pyside6=6.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip:
      - deepinv==0.4.1
